### ISSUE TITLE
improve tik tok user not found error

### ISSUE THREAD

**Issue by mesqueeb** [egoist/follower-count#21]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3253920/163658427-5eceacb0-ca77-4748-8519-e57117266990.png">

**Comment by mesqueeb** [comment]
actually, the error code of tiktok seems to be `404` but `getFollowerCountByType` doesn't pass along the code, only the message

**Comment by egoist** [comment]
you can access `error.response?.status`
